default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
  adapter: mysql2
  database: dev
  username: root
  password: 
  host: localhost
  port: 3306
  encoding: utf8

development:
  <<: *default
#  database: db/development.sqlite3

test:
  <<: *default
#  database: db/test.sqlite3

production:
  <<: *default
#  database: db/production.sqlite3
